import {
  updateVehicleImage,
  removeVehicleImage,
  numberPlateSelected,
  updateIsLicensePlateUploaded,
  categoryVariant,
  file_Details,
  clearNewInspection,
  clear_Tires,
  skipLeft,
  skipLeftCorners,
  skipRight,
  skipRightCorners,
  setVehicleType,
  setLicensePlateNumber,
  clearInspectionImages,
  setCompanyId,
  setRequired,
  batchUpdateVehicleImages,
  getMileage,
  setFeedback,
  setMileageVisible,
  setPlateNumberVisible,
  setTriggerTireStatusCheck,
  setMileage,
  setMileageMessage,
  setImageDimensions,
  setFlashMode,
} from './NewInspectionAction';
import {signIn, signOut, sessionExpired, setVehiclesList} from './AuthAction';
import {
  fetchInspectionReviewed,
  clearInspectionReviewed,
} from './InspectionReviewedAction';
import {
  fetchInspectionInProgress,
  deleteInspection,
  clearInspectionInProgress,
} from './InspectionInProgressAction';
import {setLoading, showToast, hideToast} from './UIActions';
import {
  setDevice,
  clearDevice,
  setDeviceTrip,
  setComment,
  setTripsList,
  setNewTrip,
  clearTrip,
  setVehicleID,
  setUserDeviceDetails,
  setUserStartTripDetails,
} from './DeviceAction';

import {
  addCrashData,
  updateCrashStatus,
  addThresholdEvent,
  updateCrashConfig,
  setCrashError,
  clearCrashEvents,
} from './CrashDetectionActions';

export {
  updateVehicleImage,
  removeVehicleImage,
  numberPlateSelected,
  signIn,
  signOut,
  setVehiclesList,
  fetchInspectionReviewed,
  clearInspectionReviewed,
  fetchInspectionInProgress,
  deleteInspection,
  clearInspectionInProgress,
  updateIsLicensePlateUploaded,
  categoryVariant,
  file_Details,
  setLoading,
  showToast,
  hideToast,
  clearNewInspection,
  clear_Tires,
  skipLeft,
  skipLeftCorners,
  skipRight,
  skipRightCorners,
  setVehicleType,
  setLicensePlateNumber,
  clearInspectionImages,
  setCompanyId,
  sessionExpired,
  setRequired,
  batchUpdateVehicleImages,
  getMileage,
  setFeedback,
  setMileageVisible,
  setPlateNumberVisible,
  setTriggerTireStatusCheck,
  setMileage,
  setMileageMessage,
  setImageDimensions,
  setFlashMode,
  setDevice,
  clearDevice,
  setDeviceTrip,
  setComment,
  setTripsList,
  setNewTrip,
  clearTrip,
  setVehicleID,
  setUserDeviceDetails,
  setUserStartTripDetails,
  // Crash Detection Actions
  addCrashData,
  updateCrashStatus,
  addThresholdEvent,
  updateCrashConfig,
  setCrashError,
  clearCrashEvents,
};
