export const Types = {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  UPDATE_VEHICLE_IMAGE: 'UPDATE_VEHICLE_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  CLEAR_TIRES: 'CLEAR_TIRES',
  CLEAR_NEW_INSPECTION: 'CLEAR_NEW_INSPECTION',
  SELECTED_INSPECTION_ID: 'SELECTED_INSPECTION_ID',
  COMPANY_ID: 'COMPANY_ID',
  LICENSE_PLATE_NUMBER: 'LICENSE_PLATE_NUMBER',
  CLEAR_INSPECTION_IMAGES: 'CLEAR_INSPECTION_IMAGES',
  SKIP_LEFT: 'SKIP_LEFT',
  SKIP_LEFT_CORNERS: 'SKIP_LEFT_CORNERS',
  SKIP_RIGHT: 'SKIP_RIGHT',
  SKIP_RIGHT_CORNERS: 'SKIP_RIGHT_CORNERS',

  GET_INSPECTION_REVIEWED: 'GET_INSPECTION_REVIEWED',
  CLEAR_INSPECTION_REVIEWED: 'CLEAR_INSPECTION_REVIEWED',

  GET_INSPECTION_IN_PROGRESS: 'GET_INSPECTION_IN_PROGRESS',
  REMOVE_INSPECTION: 'REMOVE_INSPECTION',
  CLEAR_INSPECTION_IN_PROGRESS: 'CLEAR_INSPECTION_IN_PROGRESS',

  IS_LICENSE_PLATE_UPLOADED: 'IS_LICENSE_PLATE_UPLOADED',
  VEHICLE_TYPE: 'VEHICLE_TYPE',
  CATEGORY_VARIANT: 'CATEGORY_VARIANT',
  FILE_DETAILS: 'FILE_DETAILS',

  SET_LOADING: 'SET_LOADING',
  SET_IMAGE_DIMENSIONS: 'SET_IMAGE_DIMENSIONS',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  SET_REQUIRED: 'SET_REQUIRED',
  BATCH_UPDATE_VEHICLE_IMAGES: 'BATCH_UPDATE_VEHICLE_IMAGES',
  SET_MILEAGE: 'SET_MILEAGE',
  SET_MILEAGE_MESSAGE: 'SET_MILEAGE_MESSAGE',
  SET_MILEAGE_VISIBLE: 'SET_MILEAGE_VISIBLE',
  SET_FEEDBACK: 'SET_FEEDBACK',
  SET_PLATE_NUMBER_VISIBLE: 'SET_PLATE_NUMBER_VISIBLE',
  SET_TRIGGER_TIRE_STATUS_CHECK: 'SET_TRIGGER_TIRE_STATUS_CHECK',
  FLASH_MODE: 'FLASH_MODE',

  DEVICE_CONNECTED: 'DEVICE_CONNECTED',
  DEVICE_DISCONNECTED: 'DEVICE_DISCONNECTED',

  // Crash Detection Types
  ADD_CRASH_EVENT: 'ADD_CRASH_EVENT',

  SET_FIRST_TIME_OPEN: 'SET_FIRST_TIME_OPEN',
  SET_SHOW_INSTRUCTIONS: 'SET_SHOW_INSTRUCTIONS',

  ADD_CRASH_DATA: 'ADD_CRASH_DATA',
  UPDATE_CRASH_STATUS: 'UPDATE_CRASH_STATUS',
  ADD_THRESHOLD_EVENT: 'ADD_THRESHOLD_EVENT',
  UPDATE_CRASH_CONFIG: 'UPDATE_CRASH_CONFIG',
  SET_CRASH_ERROR: 'SET_CRASH_ERROR',
  CLEAR_CRASH_EVENTS: 'CLEAR_CRASH_EVENTS',
};
