export const Types = {
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  UPDATE_VEHICLE_IMAGE: 'UPDATE_VEHICLE_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  CLEAR_TIRES: 'CLEAR_TIRES',
  CLEAR_NEW_INSPECTION: 'CLEAR_NEW_INSPECTION',
  SELECTED_INSPECTION_ID: 'SELECTED_INSPECTION_ID',
  COMPANY_ID: 'COMPANY_ID',
  LICENSE_PLATE_NUMBER: 'LICENSE_PLATE_NUMBER',
  CLEAR_INSPECTION_IMAGES: 'CLEAR_INSPECTION_IMAGES',
  SKIP_LEFT: 'SKIP_LEFT',
  SKIP_LEFT_CORNERS: 'SKIP_LEFT_CORNERS',
  SKIP_RIGHT: 'SKIP_RIGHT',
  SKIP_RIGHT_CORNERS: 'SKIP_RIGHT_CORNERS',

  GET_INSPECTION_REVIEWED: 'GET_INSPECTION_REVIEWED',
  CLEAR_INSPECTION_REVIEWED: 'CLEAR_INSPECTION_REVIEWED',

  GET_INSPECTION_IN_PROGRESS: 'GET_INSPECTION_IN_PROGRESS',
  REMOVE_INSPECTION_IN_PROGRESS: 'REMOVE_INSPECTION_IN_PROGRESS',
  CLEAR_INSPECTION_IN_PROGRESS: 'CLEAR_INSPECTION_IN_PROGRESS',

  IS_LICENSE_PLATE_UPLOADED: 'IS_LICENSE_PLATE_UPLOADED',
  VEHICLE_TYPE: 'VEHICLE_TYPE',
  CATEGORY_VARIANT: 'CATEGORY_VARIANT',
  FILE_DETAILS: 'FILE_DETAILS',

  SET_LOADING: 'SET_LOADING',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
};
