import { StyleSheet } from 'react-native';
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from 'react-native-responsive-screen';
import { colors } from '../../../Assets/Styles';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.royalBlue },
  blueHeaderContainer: { backgroundColor: colors.royalBlue },
  flowHeader: { paddingHorizontal: wp(5.3), paddingTop: hp(0.5), paddingBottom: hp(2.2) },
  cardWrapper: { flex: 1, borderTopLeftRadius: 20, borderTopRightRadius: 20, backgroundColor: colors.white },
  contentContainer: { paddingHorizontal: wp(4.5), paddingVertical: hp(2.2), gap: hp(1.5), paddingBottom: hp(3.5) },
  title: { fontSize: wp(5), fontWeight: '700', color: colors.white },
  subtitle: { color: '#D6E3F2', fontSize: wp(3.3) },
  stepText: { color: '#D6E3F2', fontSize: wp(3.2), marginTop: hp(0.2) },
  card: { padding: wp(4), gap: hp(1.1) },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  badge: {
    backgroundColor: colors.orangePeel,
    color: colors.white,
    borderRadius: wp(10),
    paddingHorizontal: wp(2.7),
    paddingVertical: hp(0.45),
    overflow: 'hidden',
    fontSize: wp(2.7),
    fontWeight: '600',
  },
  cardTitle: { fontSize: wp(4.3), fontWeight: '700' },
  cardDescription: { color: colors.steelGray, fontSize: wp(3.25) },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: hp(1) },
  statItem: { alignItems: 'center', flex: 1 },
  statValue: { fontSize: wp(4), fontWeight: '700' },
  statLabel: { fontSize: wp(2.8), color: colors.steelGray, marginTop: hp(0.4), textAlign: 'center' },
  ctaButton: { width: '100%', borderRadius: wp(3), marginTop: hp(0.5) },
  heroCard: {
    backgroundColor: colors.royalBlue,
    borderRadius: 20,
    padding: wp(5),
    gap: hp(0.9),
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.orangePeel,
    color: colors.white,
    borderRadius: wp(10),
    paddingHorizontal: wp(3),
    paddingVertical: hp(0.45),
    overflow: 'hidden',
    fontSize: wp(2.8),
    fontWeight: '600',
  },
  heroButton: { width: wp('45%'),height: hp('5%'),justifyContent: 'center',alignItems: 'center' },
  heroStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.25)',
    marginTop: hp(1.2),
    paddingTop: hp(1.3),
  },
  heroStatValue: { color: colors.white, fontSize: wp(4.2), fontWeight: '700' },
  heroStatLabel: { color: '#D6E3F2', fontSize: wp(2.7), marginTop: hp(0.3), textAlign: 'center' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: wp(1), marginTop: hp(0.8) },
  sectionTitle: { fontSize: wp(3.9), fontWeight: '600' },
  sectionLink: { color: colors.oceanBlue, fontSize: wp(3.1), fontWeight: '600' },
  eventCard: {
    padding: wp(3.6),
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2.8),
    marginVertical: hp(0.5),
  },
  eventIcon: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(2.5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventIconGreen: { backgroundColor: '#DCFCE7' },
  eventIconAmber: { backgroundColor: '#FEF3C7' },
  eventIconText: { fontWeight: '700', color: colors.royalBlue, fontSize: wp(3.2) },
  eventInfo: { flex: 1 },
  eventStation: { fontSize: wp(3.5), fontWeight: '600' },
  eventMeta: { marginTop: hp(0.25), color: colors.steelGray, fontSize: wp(2.9) },
  eventRight: { alignItems: 'flex-end' },
  eventAmount: { fontWeight: '700', fontSize: wp(3.5) },
  statusBadge: {
    marginTop: hp(0.35),
    fontSize: wp(2.5),
    paddingHorizontal: wp(2.3),
    paddingVertical: hp(0.25),
    borderRadius: wp(3),
    overflow: 'hidden',
    fontWeight: '600',
  },
  statusVerified: { color: '#16A34A', backgroundColor: '#DCFCE7' },
  statusReview: { color: '#D97706', backgroundColor: '#FEF3C7' },
  ghostButton: {
    width: '100%',
    borderWidth: 1,
    borderColor: colors.lightSteelBlue,
    borderRadius: wp(3),
    paddingVertical: hp(1.7),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: hp(0.4),
  },
  ghostButtonText: { color: colors.steelGray, fontWeight: '600' },
  vehicleCard: { padding: wp(4), gap: hp(1), borderWidth: 2, borderColor: colors.royalBlue, backgroundColor: colors.paleBlue, borderRadius: 16 },
  vehicleCardCenter: { alignItems: 'center', justifyContent: 'center', gap: hp(1) },
  vehicleTopRow: { flexDirection: 'row', alignItems: 'center', gap: wp(3) },
  vehicleEmojiWrap: {
    width: wp(11),
    height: wp(11),
    borderRadius: wp(2.5),
    backgroundColor: colors.royalBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vehicleEmoji: { fontSize: wp(5.3) },
  vehicleTextWrap: { flex: 1 },
  vehicleName: { fontSize: wp(4.2), fontWeight: '700' },
  vehicleMeta: { color: colors.steelGray, fontSize: wp(3.2) },
  chipsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: wp(2) },
  chip: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    borderRadius: wp(2),
    paddingHorizontal: wp(2.3),
    paddingVertical: hp(0.45),
    color: colors.steelGray,
    fontSize: wp(2.7),
  },
  progressTrack: { flexDirection: 'row', gap: wp(1.1), marginTop: hp(1.3) },
  progressPip: { height: 4, borderRadius: 2, flex: 1, backgroundColor: 'rgba(255,255,255,0.2)' },
  progressPipDone: { backgroundColor: colors.orangePeel },
  progressPipActive: { backgroundColor: colors.white },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', paddingHorizontal: wp(6) },
  modalCard: { backgroundColor: colors.white, borderRadius: 16, padding: wp(5), minHeight: hp(60), justifyContent: 'space-between' },
  modalTitle: { fontWeight: '700', fontSize: wp(4), marginBottom: hp(0.8) },
  modalSub: { color: colors.steelGray, marginBottom: hp(1.2), fontSize: wp(3.1) },
  vehicleSelectionList: { maxHeight: hp(44), marginBottom: hp(1.2) },
  vehicleOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: wp(2.5),
    paddingVertical: hp(1.5),
    paddingHorizontal: wp(3.5),
    borderWidth: 1,
    borderColor: '#E6E6E6',
    borderRadius: 10,
    marginBottom: hp(1),
    backgroundColor: colors.white,
  },
  vehicleOptionRowSelected: {
    borderColor: colors.royalBlue,
    backgroundColor: colors.paleBlue,
  },
  radioOuter: {
    width: wp(5),
    height: wp(5),
    borderRadius: wp(2.5),
    borderWidth: 1.8,
    borderColor: colors.royalBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: wp(2.5),
    height: wp(2.5),
    borderRadius: wp(1.25),
    backgroundColor: colors.royalBlue,
  },
  vehicleOptionTextWrap: { flex: 1 },
  vehicleOptionTitle: { fontSize: wp(3.8),color: colors.black },
  vehicleOptionMeta: { color: colors.steelGray, fontSize: wp(3), marginTop: hp(0.2) },
  modalHint: { color: colors.steelGray, textAlign: 'center', marginTop: hp(1.1), fontSize: wp(3) },
  locationIconWrap: {
    height: wp(10),
    width: wp(10),
    borderRadius: wp(5),
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationIcon: { fontSize: wp(5.4) },
  locationStatusRow: { flexDirection: 'row', alignItems: 'flex-start', gap: wp(3) },
  locationTextWrap: { flex: 1 },
  locationTitleRow: { flexDirection: 'row', alignItems: 'center', gap: wp(2), marginBottom: hp(0.3) },
  gpsBadge: {
    backgroundColor: '#DCFCE7',
    color: '#16A34A',
    fontSize: wp(2.4),
    fontWeight: '700',
    paddingHorizontal: wp(2),
    paddingVertical: hp(0.2),
    borderRadius: wp(3),
    overflow: 'hidden',
  },
  coordsText: {
    color: '#9CA3AF',
    fontSize: wp(2.7),
    marginTop: hp(0.35),
    letterSpacing: 0.3,
  },
  locationRetry: {
    color: '#D97706',
    fontSize: wp(3.2),
    fontWeight: '600',
    marginTop: hp(0.2),
  },
  mapContainer: {
    height: hp(31),
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    backgroundColor: '#F8F9FA',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  odometerCameraWrap: {
    height: hp(28),
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    backgroundColor: '#111827',
  },
  odometerCameraPreview: {
    ...StyleSheet.absoluteFillObject,
  },
  odometerCapturedImage: {
    width: '100%',
    height: '100%',
  },
  odometerPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: wp(6),
    backgroundColor: '#F8F9FA',
  },
  odometerResultCard: {
    padding: wp(4),
    borderWidth: 1,
    borderColor: '#E9ECEF',
    borderRadius: 14,
  },
  odometerResultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: hp(0.9),
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F5',
  },
  odometerResultRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  odometerMiles: {
    fontSize: wp(4.2),
    fontWeight: '700',
    color: '#16A34A',
  },
  uploadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: wp(2),
    paddingVertical: hp(1.2),
  },
  uploadingText: {
    color: colors.steelGray,
    fontSize: wp(3.2),
  },
});
