export const ROUTES = {
  WELCOME: 'WELCOME',
  SIGN_IN: 'SIGN_IN',
  FORGET_PASSWORD: 'FORGET_PASSWORD',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER: 'REGISTER',
  HOME: 'HOME',
  INTRO: 'INTRO',
  LICENSE_PLATE_SELECTION: 'LICENSE PLATE_SELECTION',
  NEW_INSPECTION: 'NEW INSPECTION',
  INSPECTION_REVIEWED: 'INSPECTION REVIEWED',
  INSPECTION_DETAIL: 'INSPECTION DETAIL',
  CAMERA: 'CAMERA',
  VIDEO: 'VIDEO',
  COMPLETED_INSPECTION: 'COMPLETED INSPECTION',
  INSPECTION_IN_PROGRESS: 'INSPECTION IN PROGRESS',
  LOGOUT: 'LOGOUT',
  DVIR_VEHICLE_INFO: 'DVIR_VEHICLE_INFO_CONTAINER',
  DVIR_INSPECTION_CHECKLIST: 'DVIR_INSPECTION_CHECKLIST_CONTAINER',
  TABS: 'Tabs',
  DRAWER: 'DRAWER',
  VEHICLE_INFORMATION: 'VEHICLE_INFORMATION',
  MY_PROFILE: 'PROFILE',
  MY_TRIPS: 'MY_TRIPS',
  VERIFY_FUELING: 'VERIFY_FUELING',
  CONFIRM_FUEL_VEHICLE: 'CONFIRM_FUEL_VEHICLE',
  FUEL_LOCATION_CONFIRM: 'FUEL_LOCATION_CONFIRM',
  CAPTURE_ODOMETER: 'CAPTURE_ODOMETER',
  PRE_FUEL_GAUGE: 'PRE_FUEL_GAUGE',
  CAPTURE_RECEIPT: 'CAPTURE_RECEIPT',
  FUEL_VERIFIED_SUBMIT: 'FUEL_VERIFIED_SUBMIT',
};

export const TABS = {
  HOME: 'HOME_TAB',
  REPORTS: 'REPORTS_TAB',
  INSPECTION: 'INSPECTION_TAB',
  MY_TRIPS: 'MY_TRIPS_TAB',
  PROFILE: 'PROFILE_TAB',
};

export const STACKS = {
  AUTH_STACK: 'AUTH_STACK',
};
